let test_file = {
    "_id": "C:/Transcode/source folder/x265_12bit.mkv",
    "file": "C:/Transcode/source folder/x265_12bit.mkv",
    "DB": "0foppn1Hf",
    "hasClosedCaptions": false,
    "container": "mkv",
    "ffProbeRead": "success",
    "ffProbeData": {
        "streams": [
            {
                "index": 0,
                "codec_name": "hevc",
                "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
                "profile": "Rext",
                "codec_type": "video",
                "codec_tag_string": "[0][0][0][0]",
                "codec_tag": "0x0000",
                "width": 1920,
                "height": 1080,
                "coded_width": 1920,
                "coded_height": 1080,
                "closed_captions": 0,
                "has_b_frames": 2,
                "sample_aspect_ratio": "1:1",
                "display_aspect_ratio": "16:9",
                "pix_fmt": "yuv420p12le",
                "level": 120,
                "color_range": "tv",
                "color_space": "bt709",
                "color_transfer": "bt709",
                "color_primaries": "bt709",
                "chroma_location": "left",
                "refs": 1,
                "r_frame_rate": "25/1",
                "avg_frame_rate": "25/1",
                "time_base": "1/1000",
                "start_pts": 21,
                "start_time": "0.021000",
                "disposition": {
                    "default": 1,
                    "dub": 0,
                    "original": 0,
                    "comment": 0,
                    "lyrics": 0,
                    "karaoke": 0,
                    "forced": 0,
                    "hearing_impaired": 0,
                    "visual_impaired": 0,
                    "clean_effects": 0,
                    "attached_pic": 0,
                    "timed_thumbnails": 0,
                    "captions": 0,
                    "descriptions": 0,
                    "metadata": 0,
                    "dependent": 0,
                    "still_image": 0
                },
                "tags": {
                    "DURATION": "00:00:21.341000000"
                }
            },
            {
                "index": 1,
                "codec_name": "aac",
                "codec_long_name": "AAC (Advanced Audio Coding)",
                "profile": "LC",
                "codec_type": "audio",
                "codec_tag_string": "[0][0][0][0]",
                "codec_tag": "0x0000",
                "sample_fmt": "fltp",
                "sample_rate": "48000",
                "channels": 2,
                "channel_layout": "stereo",
                "bits_per_sample": 0,
                "r_frame_rate": "0/0",
                "avg_frame_rate": "0/0",
                "time_base": "1/1000",
                "start_pts": 0,
                "start_time": "0.000000",
                "disposition": {
                    "default": 1,
                    "dub": 0,
                    "original": 0,
                    "comment": 0,
                    "lyrics": 0,
                    "karaoke": 0,
                    "forced": 0,
                    "hearing_impaired": 0,
                    "visual_impaired": 0,
                    "clean_effects": 0,
                    "attached_pic": 0,
                    "timed_thumbnails": 0,
                    "captions": 0,
                    "descriptions": 0,
                    "metadata": 0,
                    "dependent": 0,
                    "still_image": 0
                },
                "tags": {
                    "title": "Stereo",
                    "DURATION": "00:00:21.375000000"
                }
            }
        ]
    },
    "file_size": 5.5908203125,
    "video_resolution": "1080p",
    "fileMedium": "video",
    "video_codec_name": "hevc",
    "audio_codec_name": "",
    "lastPluginDetails": "none",
    "processingStatus": false,
    "createdAt": 1641046232238,
    "bit_rate": 2194114.619883041,
    "statSync": {
        "dev": 3832468976,
        "mode": 33060,
        "nlink": 1,
        "uid": 0,
        "gid": 0,
        "rdev": 0,
        "blksize": 4096,
        "ino": 16607023626295196,
        "size": 5862400,
        "blocks": 11456,
        "atimeMs": 1641046232224.5464,
        "mtimeMs": 1568393675000,
        "ctimeMs": 1623257005040.535,
        "birthtimeMs": 1640954833759.324,
        "atime": "2022-01-01T14:10:32.225Z",
        "mtime": "2019-09-13T16:54:35.000Z",
        "ctime": "2021-06-09T16:43:25.041Z",
        "birthtime": "2021-12-31T12:47:13.759Z"
    },
    "HealthCheck": "",
    "TranscodeDecisionMaker": "",
    "lastHealthCheckDate": 0,
    "holdUntil": 0,
    "lastTranscodeDate": 0,
    "infoLog": "",
    "bumped": false,
    "history": "",
    "oldSize": 0,
    "newSize": 0,
    "videoStreamIndex": 0,
    "meta": {
        "SourceFile": "C:/Transcode/source folder/x265_12bit.mkv",
        "errors": [],
        "Duration": 21.375,
        "ExifToolVersion": 12.21,
        "FileName": "x265_12bit.mkv",
        "Directory": "C:/Transcode/source folder",
        "FileSize": "5.6 MiB",
        "FileModifyDate": {
            "year": 2019,
            "month": 9,
            "day": 13,
            "hour": 17,
            "minute": 54,
            "second": 35,
            "millisecond": 0,
            "tzoffsetMinutes": 60,
            "rawValue": "2019:09:13 17:54:35+01:00"
        },
        "FileAccessDate": {
            "year": 2022,
            "month": 1,
            "day": 1,
            "hour": 14,
            "minute": 10,
            "second": 31,
            "millisecond": 0,
            "tzoffsetMinutes": 0,
            "rawValue": "2022:01:01 14:10:31+00:00"
        },
        "FileCreateDate": {
            "year": 2021,
            "month": 12,
            "day": 31,
            "hour": 12,
            "minute": 47,
            "second": 13,
            "millisecond": 0,
            "tzoffsetMinutes": 0,
            "rawValue": "2021:12:31 12:47:13+00:00"
        },
        "FilePermissions": "-r--r--r--",
        "FileType": "MKV",
        "FileTypeExtension": "mkv",
        "MIMEType": "video/x-matroska",
        "EBMLVersion": 1,
        "EBMLReadVersion": 1,
        "DocType": "matroska",
        "DocTypeVersion": 4,
        "DocTypeReadVersion": 2,
        "TimecodeScale": "1 ms",
        "MuxingApp": "Lavf58.20.100",
        "WritingApp": "HandBrake 1.2.2 2019022300",
        "DateTimeOriginal": {
            "year": 2019,
            "month": 9,
            "day": 13,
            "hour": 16,
            "minute": 50,
            "second": 12,
            "millisecond": 0,
            "tzoffsetMinutes": 0,
            "rawValue": "2019:09:13 16:50:12Z"
        },
        "VideoFrameRate": 25,
        "ImageWidth": 1920,
        "ImageHeight": 1080,
        "TrackNumber": 2,
        "TrackName": "Stereo",
        "TrackLanguage": "und",
        "CodecID": "A_AAC",
        "TrackType": "Audio",
        "AudioChannels": 2,
        "AudioSampleRate": 48000,
        "TagName": "DURATION",
        "TagString": "00:00:21.375000000",
        "ImageSize": "1920x1080",
        "Megapixels": 2.1
    },
    "mediaInfo": {
        "@ref": "",
        "track": [
            {
                "@type": "General",
                "UniqueID": "321923528548416770052330454517141864701",
                "VideoCount": "1",
                "AudioCount": "1",
                "Format": "Matroska",
                "Format_Version": "4",
                "FileSize": "5862400",
                "Duration": "21.375",
                "OverallBitRate": "2194115",
                "FrameRate": "25.000",
                "FrameCount": "533",
                "IsStreamable": "Yes",
                "Encoded_Date": "UTC 2019-09-13 16:50:12",
                "Encoded_Application": "HandBrake 1.2.2 2019022300",
                "Encoded_Library": "Lavf58.20.100",
                "extra": {
                    "ErrorDetectionType": "Per level 1"
                }
            },
            {
                "@type": "Video",
                "StreamOrder": "0",
                "ID": "1",
                "UniqueID": "1",
                "Format": "HEVC",
                "Format_Profile": "Format Range",
                "Format_Level": "4",
                "Format_Tier": "Main",
                "CodecID": "V_MPEGH/ISO/HEVC",
                "Duration": "21.320000000",
                "Width": "1920",
                "Height": "1080",
                "Sampled_Width": "1920",
                "Sampled_Height": "1080",
                "PixelAspectRatio": "1.000",
                "DisplayAspectRatio": "1.778",
                "FrameRate_Mode": "CFR",
                "FrameRate": "25.000",
                "FrameCount": "533",
                "ColorSpace": "YUV",
                "ChromaSubsampling": "4:2:0",
                "BitDepth": "12",
                "Delay": "0.021",
                "Encoded_Library": "x265 - 2.9:[Windows][GCC 8.2.0][64 bit] 12bit",
                "Encoded_Library_Name": "x265",
                "Encoded_Library_Version": "2.9:[Windows][GCC 8.2.0][64 bit] 12bit",
                "Encoded_Library_Settings": "cpuid=1111039 / frame-threads=2 / numa-pools=4 / wpp / no-pmode / no-pme / no-psnr / no-ssim / log-level=2 / input-csp=1 / input-res=1920x1080 / interlace=0 / total-frames=0 / level-idc=0 / high-tier=1 / uhd-bd=0 / ref=3 / no-allow-non-conformance / no-repeat-headers / annexb / no-aud / no-hrd / info / hash=0 / no-temporal-layers / open-gop / min-keyint=25 / keyint=250 / gop-lookahead=0 / bframes=4 / b-adapt=2 / b-pyramid / bframe-bias=0 / rc-lookahead=20 / lookahead-slices=6 / scenecut=40 / radl=0 / no-intra-refresh / ctu=64 / min-cu-size=8 / no-rect / no-amp / max-tu-size=32 / tu-inter-depth=1 / tu-intra-depth=1 / limit-tu=0 / rdoq-level=0 / dynamic-rd=0.00 / no-ssim-rd / signhide / no-tskip / nr-intra=0 / nr-inter=0 / no-constrained-intra / strong-intra-smoothing / max-merge=2 / limit-refs=3 / no-limit-modes / me=1 / subme=2 / merange=57 / temporal-mvp / weightp / no-weightb / no-analyze-src-pics / deblock=0:0 / sao / no-sao-non-deblock / rd=3 / no-early-skip / rskip / no-fast-intra / no-tskip-fast / no-cu-lossless / no-b-intra / no-splitrd-skip / rdpenalty=0 / psy-rd=2.00 / psy-rdoq=0.00 / no-rd-refine / no-lossless / cbqpoffs=0 / crqpoffs=0 / rc=crf / crf=22.0 / qcomp=0.60 / qpstep=4 / stats-write=0 / stats-read=0 / ipratio=1.40 / pbratio=1.30 / aq-mode=1 / aq-strength=1.00 / cutree / zone-count=0 / no-strict-cbr / qg-size=32 / no-rc-grain / qpmax=69 / qpmin=0 / no-const-vbv / sar=1 / overscan=0 / videoformat=5 / range=0 / colorprim=1 / transfer=1 / colormatrix=1 / chromaloc=0 / display-window=0 / max-cll=0,0 / min-luma=0 / max-luma=4095 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / no-opt-qp-pps / no-opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05 / no-opt-cu-delta-qp / no-aq-motion / no-hdr / no-hdr-opt / no-dhdr10-opt / no-idr-recovery-sei / analysis-reuse-level=5 / scale-factor=0 / refine-intra=0 / refine-inter=0 / refine-mv=0 / no-limit-sao / ctu-info=0 / no-lowpass-dct / refine-mv-type=0 / copy-pic=1 / max-ausize-factor=1.0 / no-dynamic-refine / no-single-sei",
                "Default": "Yes",
                "Forced": "No",
                "colour_description_present": "Yes",
                "colour_description_present_Source": "Stream",
                "colour_range": "Limited",
                "colour_range_Source": "Stream",
                "colour_primaries": "BT.709",
                "colour_primaries_Source": "Stream",
                "transfer_characteristics": "BT.709",
                "transfer_characteristics_Source": "Stream",
                "matrix_coefficients": "BT.709",
                "matrix_coefficients_Source": "Stream"
            },
            {
                "@type": "Audio",
                "StreamOrder": "1",
                "ID": "2",
                "UniqueID": "2",
                "Format": "AAC",
                "Format_Settings_SBR": "No (Explicit)",
                "Format_AdditionalFeatures": "LC",
                "CodecID": "A_AAC-2",
                "Duration": "21.375000000",
                "Channels": "2",
                "ChannelPositions": "Front: L R",
                "ChannelLayout": "L R",
                "SamplesPerFrame": "1024",
                "SamplingRate": "48000",
                "SamplingCount": "1026000",
                "FrameRate": "46.875",
                "Compression_Mode": "Lossy",
                "Delay": "0.000",
                "Delay_Source": "Container",
                "Title": "Stereo",
                "Default": "Yes",
                "Forced": "No"
            }
        ]
    },
    "tPosition": 0,
    "hPosition": 0
}

const _test_file = test_file;
export { _test_file as test_file };